### ISSUE TITLE
WebGL does not build (The name '_messageQueue' does not exist in the current context)

### ISSUE THREAD

**Issue by FME849** [clockworklabs/com.clockworklabs.spacetimedbsdk#340]
I updated the ClientSDK for Unity from `1.1.5` to `1.2.1` yesterday and got this error when I tried to build WebGL:
`Library/PackageCache/com.clockworklabs.spacetimedbsdk@f74705ae05c4/src/SpacetimeDBClient.cs(424,24): error CS0103: The name '_messageQueue' does not exist in the current context`

**Comment by bfops** [comment]
Thank you for filing this! Sorry for this issue. It looks like this was broken in https://github.com/clockworklabs/com.clockworklabs.spacetimedbsdk/pull/330.

**Comment by FME849** [comment]
Thank you! Please let me know when it's available to upgrade the SDK.
